language: python
python:
  - "2.7"
# command to install dependencies
install: 
- pip install -r requirements.txt
- pip install coveralls
env:
  - DB=sqlitet
# command to run tests
script:
  coverage run --source=bucketlists,tests manage.py tests

after_success:
  coveralls