language: python
python:
  - "2.7"
# command to install dependencies
install: 
- pip install -r requirements.txt
- pip install coveralls
env:
  - DB=sqlite
# command to run tests
script:
  coverage run -m unittest discover

after_success:
  coveralls